server:
  port: 9900
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        native:
#          search-locations:
#            - file:///E:/IdeaProjects/library/scloud/learn/scl-config-resources
        git:
          uri: https://github.com/liuff2513/library
          searchPaths: scloud/learn/scl-config-resources
          username: liuff2513@163.com
          password: liuhaifei6174
          label: master
#  profiles:
#    active:
#      - native
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8761/eureka/,http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8762/eureka/
    instance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）
