server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: slave1
  # 安全认证的配置
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8762/eureka/
      nstance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）

---

server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles: slave2
  # 安全认证的配置
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8761/eureka/
      nstance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）