server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: slave1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---

server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles: slave2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/