server:
  port: 8901
spring:
  application:
    name: eureka-service-invoker
eureka:
  instance:
    hostname: slave1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
