server:
  port: 8901
spring:
  application:
    name: eureka-service-invoker
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8761/eureka/,http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8762/eureka/