#author feifei.liu
version: "3"
services:
  # elk
  elk:
    image: sebp/elk
    container_name: elk
    restart: always
    ports:
      - 5601:5601
      - 9200:9200
      - 9300:9300
      - 5044:5044
    volumes:
      - ./elasticsearch:/var/lib/elasticsearch
    networks:
      - elk-network
  # filebeat
  filebeat:
    image: prima/filebeat
    container_name: filebeat
    restart: always
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - ./filebeat/data:/data
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      - elk-network

  # test-service
  test-service:
    image: bys-cd.chinacloudapp.cn/library/mysql:5.7
    container_name: elk-test-service
    restart: always
    labels:
      service: test-service
    # logging设置增加labels.service
    logging:
      options:
        labels: "service"
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "100085"
      MYSQL_USER: "bys"
      MYSQL_PASSWORD: "bys2018"
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge
