server:
  port: 9901
spring:
  application:
    name: bpm-service
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8761/eureka/,http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@localhost:8762/eureka/
    instance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）