server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: server1
  # 安全认证配置
  security:
    user:
      name: ${REGISTRY_NAME:admin}
      password: ${REGISTRY_PASSWORD:admin}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@${EUREKA_HOST:localhost}:8762/eureka/
      nstance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）

---

server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles: server1
  # 安全认证配置
  security:
    user:
      name: ${REGISTRY_NAME:admin}
      password: ${REGISTRY_PASSWORD:admin}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${REGISTRY_NAME:admin}:${REGISTRY_PASSWORD:admin}@${EUREKA_HOST:localhost}:8761/eureka/
      nstance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）