server:
  port: 8801
spring:
  application:
    name: eureka-cloud-service-provider
  profiles: slave1
eureka:
  instance:
    hostname: slave1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

---

server:
  port: 8802
spring:
  application:
    name: eureka-cloud-service-provider
  profiles: slave2
eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
