server:
  port: 8801
spring:
  application:
    name: eureka-service-provider
  profiles: slave1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）

---

server:
  port: 8802
spring:
  application:
    name: eureka-service-provider
  profiles: slave2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance-info-replication-interval-seconds: 30 #健康自检定时周期（默认30秒）
