#============================================================================
# 具体配置 可以参考
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#============================================================================
# banner
banner:
  charset: UTF-8
  location: classpath:banner.txt

# 应用属性配置
spring:
  application:
    name: scheduler
    version: v1.0.0
  # WARNING: `spring.config.name` and `spring.config.location` are used very early to
  # determine which files have to be loaded so they have to be defined as an environment
  # property (typically OS env, system property or command line argument).
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    converters:
      preferred-json-mapper: jackson
    # multipart 配置
    multipart:
      enabled: true
      file-size-threshold: 0
      location: /
      max-file-size: 1MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.16.58:5432/test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  jackson:
    serialization: true
  thymeleaf:
    enabled: true
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html;charset=UTF-8
    mode: HTML5
    prefix: classpath:/views/
    suffix: .html
    encoding: UTF-8

#服务端配置
server:
  port: ${port:54321}
  context-path: /
  compression:
    enabled: true

# 配置文件名称，内部加载使用