version: '2'
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: es1
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - CAP_IPC_LOCK
    volumes:
      - ./es1/data:/usr/share/elasticsearch/data:rw
      - ./es1/logs:/user/share/elasticsearch/logs:rw
      - ./es1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - esnet
  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: es2
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - CAP_IPC_LOCK
    volumes:
      - ./es2/data:/usr/share/elasticsearch/data:rw
      - ./es2/logs:/user/share/elasticsearch/logs:rw
      - ./es2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9202:9200
      - 9302:9300
    links:
      - es1
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  esnet:
    driver: bridge