#server.port=8801
spring:
  application:
    name: eureka-service-provider-a
server:
  port: 8801
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
