spring:
  application:
    name: eureka-server-a
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # 是否将自己的信息注册到Eureka服务器(防止将自己注册到自己出现启动异常)
    fetchRegistry: false # 是否到Eureka服务器中抓取注册信息