version: 1.0.beta
services:
  # web
  web:
    image: httpd
    ports:
      - 91:80
    links:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.174.201:24224
        tag: httpd.access

  # fluentd
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp

  # elasticsearch
  elasticsearch:
    image: elasticsearch:7.0.1
    expose:
      - 9200
    ports:
      - 9200:9200

  # kibana
  kibana:
    image: kibana:7.0.1
    links:
      - elasticsearch
    ports:
      - 5601:5601
