LANG: "zh_CN.UTF-8"
LANGUAGE: "zh_CN:zh:en_US:en"
BaseURL: 10.8.7.63
DB_HOST: 10.8.7.69
DB_PORT: 3306
DB_USER: root
DB_PSWD: 100085
DRUID_USER: root
DRUID_PSWD: 100085
REDIS_HOST: 10.8.7.69
REDIS_PORT: 6379
REDIS_PSWD: beyondsoft
LOCAL_IP: 10.8.7.69
EUREKA_HOST: 10.8.7.69
EUREKA_PORT: 8761
ESOMP_USER_SECRET: '%V^M5Hr1'
ESBMP_USER_SECRET: '2MR@KX^v'
ESMMP_USER_SECRET: 'mMR@KXx'
SERVICE_SECRET: 'GtY*W1B'
FASTDFS_TRACKER_HOST: 10.8.7.69
FASTDFS_TRACKER_PORT: 22122
AUTHENTICATION_DATABASE: bpo_esbmp
MONGO_HOST: 10.8.7.69
MONGO_PORT: 27017
MONGO_USER: bys
MONGO_PSWD: bys2018
MONGO_DATABASE_NAME: bpo_esbmp
PROFILES_ACTIVE: dev
SSL_PATH: /opt/cert/2075892_salary.1boyun.com.pfx
XXL_JOB_HOST: 10.8.7.69
XXL_JOB_PORT: 8090
XXL_JOB_EXECUTOR_IP: 10.8.7.69
XXL_JOB_EXECUTOR_PORT: 9199
#REGISTRY_NAME: beyondSoft
#REGISTRY_PASSWORD: beyondSoft2018.com
REGISTRY_HOST: localhost
REGISTRY_PORT: 8761
REGISTRY_NAME: admin
REGISTRY_PASSWORD: admin
